# Generated by Django 3.1.1 on 2020-09-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='head_content',
            field=models.TextField(default='head-content', max_length=100),
        ),
    ]
