# Generated by Django 3.1.1 on 2020-09-10 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_head_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='head_content',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
